DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS CUSTOMER_PURCHASE_HISTORY;

CREATE TABLE CUSTOMERS (
    ID INT IDENTITY(1000,1)  PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    SEX CHAR NOT NULL ,
    CITY VARCHAR(50)NOT NULL ,
    ZIP INT(5) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL
);

CREATE TABLE CUSTOMER_PURCHASE_HISTORY (
ID INT IDENTITY(1,1)  PRIMARY KEY,
   CUST_ID INT,
   FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(ID),
   PURCHASE_CODE VARCHAR(10) NOT NULL,
   PURCHASE_NUM  VARCHAR(100) NOT NULL,
   PURCHASE_AMOUNT DECIMAL NOT NULL,
   PURCHASE_DATE DATE NOT NULL
);