INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('MIKE','JOHNSON','M','COLUMBUS','66200','COLUMBUS ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('NANCY','WHITE','F','OHIO','66201','OHIO ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('MARIA','GOMEZ','F','CALIFORNIA','66202','CALIFORNIA ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('TARO','TANAKA','M','NORTH CAROLINA','66203','NORTH CAROLINA ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('BOB','CLINTON','M','TEXAS','66204','TEXAS ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('PAUL','SMITH','M','NEW YORK','66205','NEW YORK ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('JOHN','DALES','M','CONNECTICUT','66206','CONNECTICUT ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('MICHAEL','JACKSON','M','MISSOURI','66207','MISSOURI ADDRESS');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME,SEX,CITY,ZIP,ADDRESS) VALUES ('PERRY','COPUS','M','FLORIDA','66208','FLORIDA ADDRESS');


INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1000,'P001','3','100','2022-07-03');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1000,'P002','4','50','2022-06-03');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1001,'P010','12','10','2022-05-27');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1002,'P001','3','120','2022-07-02');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1000,'P004','3','180','2022-07-20');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1002,'P001','3','108','2022-08-03');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1003,'P001','3','120.75','2022-08-15');
INSERT INTO CUSTOMER_PURCHASE_HISTORY (CUST_ID, PURCHASE_CODE, PURCHASE_NUM,PURCHASE_AMOUNT,PURCHASE_DATE) VALUES (1000,'P008','3','100','2022-08-03');